# data parameters
dataset_name: imagenet
data_with_subfolder: True
# daa233's folder: /media/ouc/4T_A/datasets/ImageNet/ILSVRC2012_img_train/
input_images_path: input_dataset  # cel original e mai sus ^
input_masked_images_path: input_dataset_masked
val_data_path:
inpainting_model_params: inpainting_model_params

mask_pos: [100, 100]

resume: 
image_shape: [256, 256, 3]
mask_shape: [128, 128]
mask_batch_same: True
max_delta_shape: [32, 32]
margin: [0, 0]
discounted_mask: True
spatial_discounting_gamma: 1.0
random_crop: True
mask_type: hole     # hole | mosaic
mosaic_unit_size: 12

# training parameters
expname: benchmark
cuda: True # True
gpu_ids: [0] # [0, 1, 2]    # set the GPU ids to use, e.g. [0] or [1, 2]
num_workers: 4 # 4
lr: 0.0004
beta1: 0.5
beta2: 0.9
n_critic: 5 # 5
print_iter: 100
viz_iter: 50 # 1000
snapshot_save_iter: 100 # 5000

# loss weight
coarse_l1_alpha: 1.2
l1_loss_alpha: 1.2
ae_loss_alpha: 1.2
global_wgan_loss_alpha: 1.
gan_loss_alpha: 0.001
wgan_gp_lambda: 10

# network parameters
netG:
  input_dim: 3
  ngf: 32

netD:
  input_dim: 3
  ndf: 64

# resize
size_for_super_res_input: 200

super_res_upscale_factor: 2

resume_params: True
resume_iteration: 1000

super_res_input_path: output_after_inpainting
super_res_image_shape: [200, 200, 3]
